import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`bg-slate-800 text-slate-50 ${inter.className}`}>
        <main className="max-w-[1200px] flex justify-center items-center min-h-svh mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
